### ISSUE TITLE
EP安装ROS

### ISSUE THREAD

**Issue by VickyCas** [QiayuanLiao/EP-ROS#1]
@qiayuanliao 您好，请问ROS安装在哪里呢，Robomaster EP的运动控制板是STM32，如何安装到ROS呢，是需要接一个外接的计算平台吗？

**Comment by qiayuanl** [comment]
此程序是运行在与EP处于同一个网络环境的PC主机上的，可以是树莓派、笔记本、妙算等

**Comment by VickyCas** [comment]
好的，明白了，谢谢分享！
